### ISSUE TITLE
Timestamps on SD card

### ISSUE THREAD

**Issue by DarioC02** [RoboTeamTwente/basestation_3.0#42]
Overview of the current state of the timestamps and where we'll go next.

**Comment by DarioC02** [comment]
Currently on the basestation, we add 'timestamps' by using the time.time() method. This will return the unix time, where up until the decimal point the unit is in seconds and after the units are milliseconds. 

In the current state of the code, the timestamps are in integers 32 bits. On the robot side of things, every time we receive a new packet, we store that timestamp. In the control loop, we then increment the timestamp by 10, as the loop is called every 10 ms. 

Issue with the current code:
- At the moment the code has a precision of 1 second. As the base station sends 60 packets to every robot in a second, the increment is being overwritten. This results in multiple feedback packets with the same time. 

Solution 1:
- This issue can be solved by incrementing the size of the timestamps we are sending. 
- If we want the precision to be for 1 ms, the timestamps can be as follows: time.time() * 1000.
- Then in the control loop we increment here by 10
- By multiplying by 1000, the number of bits needed is now 42 bits. However as we are working with bytes, we need a multiples of 8, therefore we need 48 bits for this new timestamp.
- Which will result in 6 bits not being used

Solution 2:
- The other solution is where we multiply by 100. here we will need 38 bits.
- In this case, 5 bytes (40 bits) will be able to represent the ms.
- Here the control loop will increment by 1

Side marks:
The question now arises wither or not the packet should be sent in ms or,  we let the robot add the ms side while the packet is transmitted in seconds i.e unix in seconds + 0.01. I (Dario) believe, going with solution 2 and making the PC send the timestamps as 5 bytes is the easiest solution, from here we let the robot increment the time stamp by 1. And the timestamp is only replaced if and only if the new timestamp is different from the current one.  I do believe further research is needed in checking if incrementing by 1 is the correct choice, during testing the robot sent 23 packets before the timestamps was replaced. Technically it would mean that , 23 packets were sent (by the robot)in the span of 16 ms. Hence the issue arises when the robot increments by 1, then after 6ms the counter should technically be incremented by 6 as the new packet arrives?

**Comment by JWillegers** [comment]
Remark from Control (Jan Geert): timestamps between packets consistent is better for analyzing.
